# Generated by Django 3.2.18 on 2023-06-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='identifiant',
        ),
    ]
