# Generated by Django 3.2.18 on 2023-06-28 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globale', '0002_remove_login_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='rang',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
